# Generated by Django 3.2.5 on 2021-08-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='city',
        ),
    ]
